[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel",
            "backports.shutil_which ; python_version <'3'",
            "pyarrow<1 ; python_version <'3'",
            "pyarrow>=0.17,<1 ; python_version >='3'",
            "numpy>=1.13.1"]
